In [1]:
#Flatten
#Dropout

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [19]:
df = pd.read_csv("drive/MyDrive/DNN/sonar_dataset.csv", header=None)
df.sample(5)

0       1       2       3       4       5       6       7       8   \
16   0.0352  0.0116  0.0191  0.0469  0.0737  0.1185  0.1683  0.1541  0.1466   
8    0.0223  0.0375  0.0484  0.0475  0.0647  0.0591  0.0753  0.0098  0.0684   
142  0.0526  0.0563  0.1219  0.1206  0.0246  0.1022  0.0539  0.0439  0.2291   
114  0.0114  0.0222  0.0269  0.0384  0.1217  0.2062  0.1489  0.0929  0.1350   
147  0.0654  0.0649  0.0737  0.1132  0.2482  0.1257  0.1797  0.0989  0.2460   

         9   ...      51      52      53      54      55      56      57  \
16   0.2912  ...  0.0346  0.0158  0.0154  0.0109  0.0048  0.0095  0.0015   
8    0.1487  ...  0.0145  0.0128  0.0145  0.0058  0.0049  0.0065  0.0093   
142  0.1632  ...  0.0339  0.0149  0.0335  0.0376  0.0174  0.0132  0.0103   
114  0.1799  ...  0.0269  0.0152  0.0257  0.0097  0.0041  0.0050  0.0145   
147  0.3422  ...  0.0210  0.0361  0.0239  0.0447  0.0394  0.0355  0.0440   

         58      59  60  
16   0.0073  0.0067   R  
8    0.0059  0.0022   R  
142  0.0364  0.0208   M  
114  0.0103  0.0025   M  
147  0.0243  0.0098   M  

[5 rows x 61 columns]

In [20]:
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [21]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [22]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [23]:
X = df.drop(60, axis=1)
y = df[60]
y.head()

0    R
1    R
2    R
3    R
4    R
Name: 60, dtype: object

In [26]:
#df[60].replace({'M':0,'R':1},inplace=True)
#df

In [25]:
y = pd.get_dummies(y, drop_first=True)
y.sample(5) # R --> 1 and M --> 0

R
87   1
198  0
130  0
149  0
12   1

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

In [28]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from tensorflow.keras.layers import Flatten,Dropout,Dense

In [29]:
model=Sequential(
    [keras.layers.Dense(60, input_dim=60, activation='relu'),
     keras.layers.Dense(30, activation='relu'),
     keras.layers.Dense(15, activation='relu'),
     keras.layers.Dense(1, activation='sigmoid')

    ]
)

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 3s 4ms/step - loss: 0.6973 - accuracy: 0.5577
Epoch 2/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6712 - accuracy: 0.6603
Epoch 3/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6451 - accuracy: 0.6282
Epoch 4/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6107 - accuracy: 0.7179
Epoch 5/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5687 - accuracy: 0.7692
Epoch 6/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5251 - accuracy: 0.7500
Epoch 7/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5147 - accuracy: 0.7500
Epoch 8/100
20/20 [==============================] - 0s 3ms/step - loss: 0.4704 - accuracy: 0.7564
Epoch 9/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4340 - accuracy: 0.8397
Epoch 10/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4389 - accuracy: 0.7692
Epoch 11/

In [ ]:
model.evaluate(X_test,y_test)

2/2 [==============================] - 0s 7ms/step - loss: 0.9071 - accuracy: 0.8077


[0.9070778489112854, 0.807692289352417]

In [ ]:
y_pred=model.predict(X_test)

2/2 [==============================] - 0s 6ms/step


In [ ]:
y_pred

array([[5.52935582e-08],
       [9.41463709e-01],
       [9.99323189e-01],
       [2.31288072e-06],
       [9.99999344e-01],
       [9.99732435e-01],
       [1.83874562e-01],
       [9.99999702e-01],
       [4.51707228e-06],
       [9.99999881e-01],
       [7.53598154e-01],
       [2.01251642e-05],
       [1.55380112e-04],
       [4.04798397e-04],
       [5.74706588e-03],
       [3.23397249e-01],
       [9.99991536e-01],
       [9.53851213e-06],
       [2.64941771e-02],
       [9.99995112e-01],
       [4.80418066e-06],
       [9.99998927e-01],
       [7.56896213e-02],
       [9.99729872e-01],
       [8.22942166e-05],
       [1.07163686e-07],
       [2.34727319e-02],
       [5.06864628e-04],
       [9.99988854e-01],
       [8.58296698e-05],
       [8.09811294e-01],
       [4.88034686e-07],
       [9.59107518e-01],
       [2.08527505e-01],
       [9.99783576e-01],
       [9.99884427e-01],
       [9.99997139e-01],
       [9.93914723e-01],
       [9.99971330e-01],
       [1.37438750e-04],


In [ ]:
y_pred = np.round(y_pred)
y_pred

array([[0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [ ]:
tf.math.confusion_matrix(y_test, y_pred.reshape((-1)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[24,  3],
       [ 7, 18]], dtype=int32)>

In [ ]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test, y_pred.reshape((-1))))

              precision    recall  f1-score   support

           0       0.77      0.89      0.83        27
           1       0.86      0.72      0.78        25

    accuracy                           0.81        52
   macro avg       0.82      0.80      0.81        52
weighted avg       0.81      0.81      0.81        52



In [ ]:
model1=Sequential(
    [keras.layers.Dense(60, input_dim=60, activation='relu'),
     Dropout(0.5),
     keras.layers.Dense(30, activation='relu'),
     Dropout(0.5),
     keras.layers.Dense(15, activation='relu'),
     Dropout(0.5),
     keras.layers.Dense(1, activation='sigmoid')

    ]
)

model1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model1.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 4s 4ms/step - loss: 0.7276 - accuracy: 0.4487
Epoch 2/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6922 - accuracy: 0.5449
Epoch 3/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6940 - accuracy: 0.5256
Epoch 4/100
20/20 [==============================] - 0s 10ms/step - loss: 0.6724 - accuracy: 0.5833
Epoch 5/100
20/20 [==============================] - 0s 8ms/step - loss: 0.7149 - accuracy: 0.5000
Epoch 6/100
20/20 [==============================] - 0s 7ms/step - loss: 0.6837 - accuracy: 0.5577
Epoch 7/100
20/20 [==============================] - 0s 7ms/step - loss: 0.6828 - accuracy: 0.5192
Epoch 8/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6688 - accuracy: 0.5449
Epoch 9/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6886 - accuracy: 0.5577
Epoch 10/100
20/20 [==============================] - 0s 11ms/step - loss: 0.7087 - accuracy: 0.4872
Epoch 1

In [ ]:
model1.evaluate(X_test,y_test)

2/2 [==============================] - 0s 10ms/step - loss: 0.4822 - accuracy: 0.7500


[0.4821764826774597, 0.75]

In [ ]:
y_pred=model.predict(X_test)
y_pred = np.round(y_pred)
y_pred

2/2 [==============================] - 0s 11ms/step


array([[0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [ ]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test, y_pred.reshape((-1))))

              precision    recall  f1-score   support

           0       0.77      0.89      0.83        27
           1       0.86      0.72      0.78        25

    accuracy                           0.81        52
   macro avg       0.82      0.80      0.81        52
weighted avg       0.81      0.81      0.81        52

